### ISSUE TITLE
achexが長期ダウン中、　piesocketの無料プランが消滅

### ISSUE THREAD

**Issue by satakagi** [chirimen-oh/remote-connection#5]

**Comment by satakagi** [comment]
安全のために、やはり自前のサービスを一つは用意しておいた方が良さそう。

**Comment by satakagi** [comment]
ということで、
https://github.com/chirimen-oh/chirimen-web-socket-relay
を用意し、herokuにデプロイしました。

**Comment by sizuhiko** [comment]
herokuの無料プラン、まもなく終わっちゃいますけど heroku で大丈夫ですかね？

**Comment by dynamis** [comment]
継続安心して利用できる用に heroku に弊社で課金してます。(・・).
render にもセットアップ＆ 24 時間稼働するための uptimerobot での監視 (5 分毎に get リクエスト発生) をしています。

**Comment by gurezo** [comment]
chirimen の gmail アカウントを使えば、firebaseという選択肢もあると思います。
必要があれば、準備いたします。

**Comment by dynamis** [comment]
firebase って WebSocket サポートの入った永続 (あるいは長期・共有・継続稼働) Node サーバインスタンス立てる機能ありました？Cloud Functions のような短時間並列起動のサーバレス環境向けのアプリケーションではないのでさっとデプロイは出来ないのでは。

**Comment by gurezo** [comment]
あ、、、、、WebSocket の事忘れていました。
確認しなきゃですが、無い可能性気がします。。。。。

**Comment by dynamis** [comment]
- 取りあえず安定稼働できているモノを一つコミュニティとして提供できれば良い
- 誰でも自分で簡単にデプロイできるように用意してあげられれば良い
- 特定の非 OSS クラウドサービス環境に合わせた実装依存コードを作る方針ではないハズ

なので、heroku + render にデプロイサンプルまで稼働している部分で要件は満たし、他にも fly.io とか選択肢はありますが片っ端から post heroku サービス群にデプロイする必要もないし現状で必要十分かと。

オープンにしてると誰かが勝手に流用して負荷が高まる場合には何か対応が必要になるが、それがない限りは現状のままで良い想定をしています。
